# Generated by Django 4.2.3 on 2023-07-04 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidad', models.CharField(max_length=50, verbose_name='Habilidad')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empleado', models.CharField(max_length=60, verbose_name='Nombres')),
                ('apellido_empleado', models.CharField(max_length=60, verbose_name='Apellidos')),
                ('trabajo_empleado', models.CharField(choices=[('0', 'Contador'), ('1', 'Cantante'), ('2', 'Ecologa'), ('3', 'Futbolista')], max_length=100, verbose_name='Empleo')),
                ('nombre_completo_mpleado', models.CharField(blank=True, max_length=120, verbose_name='Nombre Completo')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamento.departamento')),
                ('habilidad', models.ManyToManyField(to='empleados.habilidades')),
            ],
        ),
    ]
