# Generated by Django 4.2.3 on 2023-07-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_departamento', models.CharField(blank=True, max_length=50, verbose_name='Nombre')),
                ('nombre_corto_departamento', models.CharField(max_length=20, verbose_name='Psudonimo')),
                ('activo_departamento', models.BooleanField(default=False, verbose_name='False')),
            ],
        ),
    ]
